Repository hmcts/ccfr-fees-register-admin-web, pull requests merged in 2018-10, with the labels that each got.

#107 Docker & Kubernetes Integration
  .dockerignore
  Dockerfile
  Jenkinsfile_CNP
  docker-compose.yml
  kubernetes/.lint.yml
  kubernetes/config.aat.yaml
  kubernetes/deployment.template.yaml
  package.json
  yarn.lock
Labels: ip:10.97.16.7, ns:fees-register-frontend-pr-107

#116 Change node version to 8.11.1
  Dockerfile
  infrastructure/main.tf
  package.json
Labels: ns:fees-register-frontend-pr-116

#113 PAY-1359 - moved to shared infra vault
  Jenkinsfile_CNP
  infrastructure/main.tf
Labels: ns:fees-register-frontend-pr-113
