Repository hmcts/ccfr-fees-register-admin-web, pull requests merged in 2022-06, with the labels that each got.

#442 cve issue fixes changes
  yarn-audit-known-issues
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-frontend-pr-442

#444 Suppress security on audit file
  Jenkinsfile_nightly
  audit.json
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-frontend-pr-444

#445 Issue fixes
  package.json
  yarn-audit-known-issues
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-frontend-pr-445

#447 fix cross browser tests and update report config
  Jenkinsfile_nightly
  acceptance-tests/saucelabs.conf.js
  package.json
  yarn.lock
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-frontend-pr-447
