Repository hmcts/ccfr-fees-register-admin-web, pull requests merged in 2023-03, with the labels that each got.

#498 CVE fix 02032023
  charts/fees-register-frontend/Chart.yaml
  yarn-audit-known-issues
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-frontend-pr-498

#499 update azurerem version
  infrastructure/main.tf
Labels: ns:fees-pay, prd:fees-register, no-changes, rel:fees-register-frontend-pr-499

#500 PAY-4884: Fix CVEs Mar 12
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:fees-pay, prd:fees-register, no-changes, rel:fees-register-frontend-pr-500, keep-helm
