Repository hmcts/ccfr-fees-register-admin-web, pull requests merged in 2023-07, with the labels that each got.

#515 PAY-6260_pipeline fix
  yarn-audit-known-issues
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-frontend-pr-515

#518 initial setup
  scripts/pa11y.js
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-frontend-pr-518

#520 PAY-6406: Update to resolve CVE
  Jenkinsfile_CNP
  package.json
  test
  yarn-audit-known-issues
  yarn.lock
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-frontend-pr-520
