Repository hmcts/ccfr-fees-register-admin-web, pull requests merged in 2023-09, with the labels that each got.

#528 PAY-6510: Nightly build pipeline fixes
  audit.json
  yarn-audit-known-issues
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-frontend-pr-528

#530 ignore zaproxy
  audit.json
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-frontend-pr-530

#531 Pay fix node version
  .github/renovate.json
  .github/workflows/ci.yml
  .nvmrc
  package.json
  yarn-audit-known-issues
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-frontend-pr-531
