Repository hmcts/ccfr-fees-register-admin-web, pull requests merged in 2023-01, with the labels that each got.

#479 cve fix
  yarn-audit-known-issues
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-frontend-pr-479

#483 cve fix
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-frontend-pr-483

#486 updated deprecated after to afterAlways
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  Jenkinsfile_parameterized
  acceptance-tests/test/end-to-end/tests/CCFeesRegister_ApproverScreenValidation_test.js
  acceptance-tests/test/end-to-end/tests/CCFeesRegister_EditorScreenValidation_test.js
  charts/fees-register-frontend/Chart.yaml
  package.json
  src/main/app/forms/validation/formValidator.ts
  src/main/app/forms/validation/validators/fractions.ts
  tsconfig.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-frontend-pr-486

#493 suppress cve
  yarn-audit-known-issues
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-frontend-pr-493

#489 Terraform version upgraded to 1.3.7
  infrastructure/.terraform-version
Labels: ns:fees-pay, prd:fees-register, no-changes, rel:fees-register-frontend-pr-489
