Repository hmcts/ccfr-fees-register-admin-web, pull requests merged in 2024-09, with the labels that each got.

#605 PAY-7319 pipeline fixes
  yarn-audit-known-issues
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-frontend-pr-605

#606 PAY-7319 pipeline fixes
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-frontend-pr-606

#607 PAY-7347 CVE pipeline fixes
  yarn-audit-known-issues
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-frontend-pr-607
