Repository hmcts/ccfr-fees-register-admin-web, pull requests merged in 2024-04, with the labels that each got.

#561 PAY-6908: CVE and build pipeline fix, nodejs updated
  .nvmrc
  charts/fees-register-frontend/Chart.yaml
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-frontend-pr-561

#562 [PAY-6999: Pipeline fixes - week beginning 8th April 2024
  package.json
  yarn.lock
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-frontend-pr-562

#568 PAY-7025 Pipeline fix
  package.json
  yarn.lock
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-frontend-pr-568

#569 Pay 7015 fix ithc login
  .gitignore
  acceptance-tests/test/end-to-end/helpers/idam_helper.js
  package.json
  src/main/app.ts
  src/main/app/idam/security.js
  src/main/server.ts
  yarn.lock
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-frontend-pr-569, enable_keep_helm
