Repository hmcts/ccfr-fees-register-admin-web, pull requests merged in 2024-06, with the labels that each got.

#576 PAY-7168 cve supression
  yarn-audit-known-issues
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-frontend-pr-576

#580 [PAY-6999: Pipeline fixes - week beginning 17 Jun 2024
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-frontend-pr-580

#581 [PAY-7194: Pipeline fixes - week beginning 17 Jun 2024
  Jenkinsfile_nightly
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-frontend-pr-581
