Repository hmcts/ccfr-fees-register-admin-web, pull requests merged in 2024-08, with the labels that each got.

#601 PAY-7231 upgrade @azure/identity pipeline fix
  package.json
  yarn.lock
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-frontend-pr-601

#600 PAY-7120
  src/main/public/js/exportexcel.js
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-frontend-pr-600

#603 PAY-7299 suppressed micromatch no supported patch
  yarn-audit-known-issues
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-frontend-pr-603

#602 PAY-7120 addressed VUL-6113 rework
  src/main/public/js/exportexcel.js
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-frontend-pr-602

#604 PAY-7302: Update to fix CVE issue
  package.json
  yarn.lock
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-frontend-pr-604
