Repository hmcts/ccfr-fees-register-admin-web, pull requests merged in 2024-07, with the labels that each got.

#582 Pay 7199 nighty dev fix
  Jenkinsfile_nightly
  src/main/app/idam/security.js
  src/main/routes/logout.ts
Labels: ns:fees-pay, prd:fees-register, enable_keep_helm, rel:fees-register-frontend-pr-582

#590 PAY-7199: Redirect issue in ccfr-fees-register-admin-web
  Jenkinsfile_nightly
  src/main/app/idam/security.js
  src/main/routes/logout.ts
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-frontend-pr-590

#599 PAY-7179: Updated to resolve vulnerability
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-frontend-pr-599
