Repository hmcts/ccfr-fees-register-admin-web, pull requests merged in 2025-07, with the labels that each got.

#661 CME-526 remove missed references to request package
  README.md
  package.json
  src/main/app/client/request.ts
  src/main/features/admin/v2/routes/dashboard.ts
  src/main/features/admin/v2/routes/draft-delete-are-you-sure.ts
  src/main/features/admin/v2/routes/fee-details.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-frontend-pr-661

#666 PAY-7974 address on-headers vulnerability
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-frontend-pr-666

#667 PAY-7974 address serialize-javascript and form-data vulnerability
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-frontend-pr-667
